theme: minima
title: Idiomatic Restrictions
author: Emanuele Messori
email: teorems@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Conundrums, temper tantrums, soul's algorithms. Coding, Python, Poetry.

# social links

github_username:  teorems

show_excerpts: true # set to false to remove excerpts on the homepage

